version: "3.9"
services:
  prometheus:
    image: "prom/prometheus"
    container_name: "prometheus-server"
    hostname: "prometheus-server"
    volumes: 
      - .:/etc/prometheus
    ports: 
      - "9090:9090"
    networks: 
      - prometheus

networks: 
  prometheus:
      name: prometheus-network
      driver: bridge