version: "3.9"
services:
  prometheus:
    image: "prom/prometheus"
    volumes: 
      - .:/etc/prometheus
    ports: 
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"